### ISSUE TITLE
Does not work with stylus-loader 4.x

### ISSUE THREAD

**Issue by zaneclaes** [naftis/craco-stylus#1] opened 2020-11-17 19:19 UTC
I just found this repo today, and it's exactly what I need. However, I could not get it to work until I downgraded `stylus-loader` to `3.x`.

Specifically:

```
node_modules/stylus-loader/dist/cjs.js??ref--5-oneOf-8-3!./src/styles/app.styl)
ValidationError: Invalid options object. Stylus Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'source'. These properties are valid:
   object { stylusOptions?, sourceMap?, webpackImporter?, additionalData? }
```

I ended up copying the source code and editing it appropriately for the new docs: https://webpack.js.org/loaders/stylus-loader/

**Comment by naftis** [comment] 2020-11-18 07:40
Hi @zaneclaes, thanks for reporting the bug. If you modified the source code, would you mind creating a pull request for fixing this? My project where I'm using this library is locked with the older Stylus, so I'm not currently using the latest versions unfortunately.

**Comment by TheSixer** [comment] 2021-01-25 11:37
Hi @zaneclaes , did you fixed this ?

**Comment by TheSixer** [comment] 2021-01-26 01:51
@naftis I'm sorry to copied you code, and published a new plugin for myself. I just want try fixing this bug to myself. I'm so sorry about that.

**Comment by naftis** [comment] 2021-01-26 07:29
@TheSixer No problem, great that you got it working. I can also create a fix for this repository from your plugin if that is okay with you :)

**Closed as completed** 2021-01-31 22:28 UTC
Labels: bug

**Comment by naftis** [comment] 2021-01-31 22:31
Hello @TheSixer @zaneclaes, released 1.1.1 with a fix to this problem. Could you verify the issue is fixed for you?

**Comment by nikitaGetman** [comment] 2022-03-15 16:11
Hi guys.I fixed it in my PR -  https://github.com/naftis/craco-stylus/pull/4

**Comment by naftis** [comment] 2022-03-15 17:00
@nikitaGetman I've released 1.2.0 with your fix to this problem.
